### ISSUE TITLE
How to hide scroll bar?

### ISSUE THREAD

**Issue by Velorum6** [dfdao/dfdao.github.io#8]
some websites have their scroll bar hidden, zkga.me it's an example of that

I tried `overflow: hidden;` in the css body, but it makes the website freeze and not able to scroll, any ideas?

**Comment by Bulmenisaurus** [comment]
Here is how dark forest does it in their [style.css](https://github.com/darkforest-eth/client/blob/54cfeb0ff87cb6ea1f2a13ff888eefd1befdc908/src/Frontend/Styles/style.css):

```css
::-webkit-scrollbar {
  width: 0px;
  background: transparent;
}
/* Hide scrollbar for Chrome, Safari and Opera */
*::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE, Edge and Firefox */
* {
  -ms-overflow-style: none; /* IE and Edge */
  scrollbar-width: none; /* Firefox */
}
```
